export * from './footer'
export * from './header'
export * from './advertise'
export * from './sideCategory'
export * from './productCollection'
export * from './brandPartners'
export * from "./productIntro"
export * from "./productComments"
export * from './productList'
export * from './paymentCard'
export * from './paymentForm'
export * from './checkOutCard'
